version: '3.7'

services:
  postgres.clubhouse:
    image: postgres:14
    restart: always
    environment:
      # POSTGRES_MULTIPLE_DATABASES: bouncecode
      POSTGRES_DB: clubhouse
      POSTGRES_USER: root
      POSTGRES_PASSWORD: clubhouseclubhouse
    volumes:
      - postgresql.clubhouse_volume:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5434:5432' # temporary
    logging:
      driver: 'json-file'
      options:
        max-size: '200k'
        max-file: '10'

volumes:
  postgresql.clubhouse:
